### PR TITLE
feat(versioning): add versioning for project

### LINKED ISSUE #11: Add some versioning
Keeping track of version is important!

### PR DESCRIPTION
**Pull request by syncush**
closes #11

### CODE REVIEW

**Review by nirolevy — APPROVED** [review]
Is that it? All you need is a variable?
I saw stuff in `setup.py` and `version` files... So I avoided the matter

**Comment by nirolevy** [comment]
> Is that it? All you need is a variable?
> I saw stuff in `setup.py` and `version` files... So I avoided the matter

@syncush

**Comment by syncush** [comment]
> > Is that it? All you need is a variable?
> > I saw stuff in `setup.py` and `version` files... So I avoided the matter
> 
> @syncush 

Well as far as I know, `setup.py` is meant for python packages. I believe that Web frameworks like django implement their own versioning method. There is no clear guideline, my PR is based on Stackoverflow approved comments.

What do you think? Is it still good?

**Comment by nirolevy** [comment]
> Well as far as I know, `setup.py` is meant for python packages. I believe that Web frameworks like django implement their own versioning method. There is no clear guideline, my PR is based on Stackoverflow approved comments.
> 
> What do you think? Is it still good?

I think so

**Comment by Guinness1759** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mh.guinness/vsix-downloader/pullRequest?prid=5464220&bid=17909356)

**Pull request merged**
